# Install antigen zsh plugin manager
[".config/zsh/antigen.zsh"]
    type = "file"
    url = "https://git.io/antigen"
    refreshPeriod = "168h"

# Install asdf environment manager
[".asdf"]
    type = "archive"
    url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.11.3.tar.gz"
    stripComponents = 1

{{- if .fonts }}
# Install Fonts to os-specific location
{{- $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}

# FiraCode NF
["{{ $fontDir }}/FiraCodeNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/FiraCode.zip"
    include = [ "Fira*Complete.ttf" ]

# CaskaydiaCove NF
["{{ $fontDir }}/CaskaydiaCoveNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/CascadiaCode.zip"
    include = [ "*.otf" ]

# Ubuntu NF
["{{ $fontDir }}/UbuntuNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Ubuntu.zip"
    include = [ "*Complete.ttf", "*Mono.ttf" ]

# Nerd Font Symbols Only
["{{ $fontDir }}/NerdFontGlyphs"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/NerdFontsSymbolsOnly.zip"
    include = ["*.ttf"]

# FiraCode
["{{ $fontDir }}/FiraCode"]
    type = "archive"
    url = "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
    stripComponents = 1
    include = ["*/FiraCode-VF.ttf"]

# VictorMono
["{{ $fontDir }}/VictorMono"]
    type = "archive"
    url = "https://rubjo.github.io/victor-mono/VictorMonoAll.zip"
    stripComponents = 1
    include = ["*/*.ttf"]

{{- end }}

# Kitty logo
# macOS: May need to run `rm /var/folders/*/*/*/com.apple.dock.iconcache; killall Dock`
[".config/kitty/kitty.app.png"]
    type = "file"
    url = "https://raw.githubusercontent.com/samholmes/whiskers/main/whiskers-tokyo.png"
