#!/bin/bash

protected_branches=("master" "main")
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for branch in "${protected_branches[@]}"; do
	if [ $current_branch = $branch ]; then
		read -p "You're about to push to '$branch', is that what you intended? [y|n] " -n 1 -r </dev/tty
		echo
		if echo $REPLY | grep -E '^[Yy]$' >/dev/null; then
			exit 0 # push will execute
		fi
		exit 1 # push will not execute
	fi
done
