[env]
_.path = [
  # Expose node module binaries without need for npm exec
  "{{config_root}}/node_modules/.bin",
]

[tools]
python = "latest"
node = "latest"
java = "21"
kubectl = "1.30"
"npm:@zed-industries/claude-agent-acp" = "latest"
"@github/copilot-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "terraform"]
